Avoid panic when ip_configuration data on firewall is null
When ipConfigurations data is null on azure firewall
steampipe throwns an error:

```
   ERROR:  rpc error: code = Unknown desc = failed to populate column
'ip_configurations': rpc error: code = Internal desc = transform
ipConfigurationData failed with panic runtime error: invalid memory
address or nil pointer dereference
````

A json dump of the firewall resource shows:

```
  "ipConfigurations": null
```